<a href="https://colab.research.google.com/github/zahra-0201/Machine-Learning/blob/main/tugas02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#sambungkan dengan gdrive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
#path folder gdrive
path = "/content/gdrive/MyDrive/SEMESTER 3/ML/praktikum/praktikum02"

In [3]:
#library pandas
import pandas as pd

In [4]:
#baca file csv yang ada di folder data
df = pd.read_csv(path + '/data/day.csv')
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [5]:
#cari jumlah total data
total = len(df)
print("Jumlah total data:", total)

Jumlah total data: 731

In [6]:
#menghitung ukuran tiap pembagian data
data_train =  int(0.8*total) #Data Training: 80% dari total dataset
data_test = total - data_train #Data Testing: 20% dari total dataset
data_val   = int(0.1 * data_train) #Data Validation: 10% dari data training

In [7]:
#membagi data data menjadi training, validation, test
train_df = df.iloc[:data_train]
test_df  = df.iloc[data_train:]
val_df = train_df.iloc[:data_val]
train_df = train_df.iloc[data_val:]

In [ ]:
print("---JUMLAH DATA---\n")
print("Data Training:", len(train_df))
print("Data Validation:", len(val_df))
print("Data Testing:", len(test_df))

---JUMLAH DATA---

Data Training: 526
Data Validation: 58
Data Testing: 147

In [ ]:
print("---5 DATA TRAINING---\n")
print(train_df.head())

---5 DATA TRAINING---

    instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
58       59  2011-02-28       1   0     2        0        1           1
59       60  2011-03-01       1   0     3        0        2           1
60       61  2011-03-02       1   0     3        0        3           1
61       62  2011-03-03       1   0     3        0        4           1
62       63  2011-03-04       1   0     3        0        5           1

    weathersit      temp     atemp       hum  windspeed  casual  registered  \
58           2  0.407273  0.400118  0.876364   0.289686      81        1365
59           1  0.266667  0.263879  0.535000   0.216425     137        1714
60           1  0.335000  0.320071  0.449583   0.307833     231        1903
61           1  0.198333  0.200133  0.318333   0.225754     123        1562
62           2  0.261667  0.255679  0.610417   0.203346     214        1730

     cnt
58  1446
59  1851
60  2134
61  1685
62  1944

In [ ]:
print("---5 DATA VALIDATION---\n")
print(val_df.head())

---5 DATA VALIDATION---

   instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0
1        2  2011-01-02       1   0     1        0        0           0
2        3  2011-01-03       1   0     1        0        1           1
3        4  2011-01-04       1   0     1        0        2           1
4        5  2011-01-05       1   0     1        0        3           1

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654
1           2  0.363478  0.353739  0.696087   0.248539     131         670
2           1  0.196364  0.189405  0.437273   0.248309     120        1229
3           1  0.200000  0.212122  0.590435   0.160296     108        1454
4           1  0.226957  0.229270  0.436957   0.186900      82        1518

    cnt
0   985
1   801
2  1349
3  1562
4  1600

In [ ]:
print("---5 DATA TESTING---\n")
print(test_df.head())

---5 DATA TESTING---

     instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
584      585  2012-08-07       3   1     8        0        2           1
585      586  2012-08-08       3   1     8        0        3           1
586      587  2012-08-09       3   1     8        0        4           1
587      588  2012-08-10       3   1     8        0        5           1
588      589  2012-08-11       3   1     8        0        6           0

     weathersit      temp     atemp       hum  windspeed  casual  registered  \
584           2  0.735833  0.697621  0.703750   0.116908    1278        5995
585           2  0.750000  0.707717  0.672917   0.110700    1263        6271
586           1  0.755833  0.699508  0.620417   0.156100    1196        6090
587           2  0.715833  0.667942  0.715833   0.238813    1065        4721
588           2  0.692500  0.638267  0.732917   0.206479    2247        4052

      cnt
584  7273
585  7534
586  7286
587  5786
588  6299